ExamWeb_ChauMinhVui/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamWeb_ChauMinhVui.Models
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> ops) : base(ops)
        {

        }
        public DbSet<Phim> Phims { get; set; }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Phim>().HasData(
             new Phim { Id = 1, TuaDe = "Chúng ta của 8 năm sau", DienVien = "Huyền Lizzie, Mạnh Trường", TrongNuoc = true, GiaVe = 150000, ThoiLuong = 110 },
             new Phim { Id = 2, TuaDe = "Avatar", DienVien = "Sam Worthington", TrongNuoc = false, GiaVe = 250000, ThoiLuong = 161 },
             new Phim { Id = 3, TuaDe = "Gặp em ngày nắng", DienVien = "Đình Tú, Anh Đào", TrongNuoc = true, GiaVe = 160000, ThoiLuong = 105 },
             new Phim { Id = 4, TuaDe = "Không ngại cưới", DienVien = "Hoàng Thùy Linh, Nhan Phúc Vinh", TrongNuoc = true, GiaVe = 120000, ThoiLuong = 150 },
             new Phim { Id = 5, TuaDe = "Gia đình đại chiến", DienVien = "Đức Khuê, Nguyệt Hằng", TrongNuoc = true, GiaVe = 130000, ThoiLuong = 120 },
             new Phim { Id = 6, TuaDe = "Kẻ Huỷ Diệt ", DienVien = "Arnold Schwarzenegger", TrongNuoc = false, GiaVe = 210000, ThoiLuong = 107 }
           );


        }
    }
}

ExamWeb_ChauMinhVui/Models/ErrorViewModel.cs
using System;

namespace ExamWeb_ChauMinhVui.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExamWeb_ChauMinhVui/Models/Phim.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExamWeb_ChauMinhVui.Models
{
    public class Phim
    {
        public int Id { get; set; }
        [ StringLength(250)]
        [Required(ErrorMessage = "Chưa nhập tiêu đề")]
        public String TuaDe { get; set; }
        [StringLength(50)]
        [Required]
        public String DienVien { get; set; }
        public Boolean TrongNuoc { get; set; }
        public double GiaVe { get; set; }
        [Range(0, double.MaxValue, ErrorMessage = "Giá không hợp lệ")]
        public int ThoiLuong { get; set; }
       
    }
}

ExamWeb_ChauMinhVui/Controllers/HomeController.cs
using ExamWeb_ChauMinhVui.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExamWeb_ChauMinhVui.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExamWeb_ChauMinhVui/Controllers/PhimController.cs
using ExamWeb_ChauMinhVui.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamWeb_ChauMinhVui.Controllers
{
    public class PhimController: Controller

    {
        private readonly ApplicationDbContext _db;

        public PhimController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var dsPhim = _db.Phims.ToList();
            var tongsoluong = _db.Phims.Sum(x => x.Id);
            var max = _db.Phims.Sum(x => x.GiaVe);
            ViewBag.SUM = tongsoluong;
            return View(dsPhim);
        }
        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Phim phim)
        {
            if (ModelState.IsValid)
            {
                _db.Phims.Add(phim);
                _db.SaveChanges();
                TempData["success"] = "Đã thêm 1 bộ phim";
                return RedirectToAction("Index");
            }
            return View(phim);
        }
        public IActionResult Update(int id)
        {
           
            var phim = _db.Phims.SingleOrDefault(x => x.Id == id);
            if (phim != null)
                return View(phim);

            return NotFound();
        }
        [HttpPost]
        public IActionResult Update(Phim phim)
        {
            if (ModelState.IsValid)
            {
                _db.Phims.Update(phim);
                _db.SaveChanges();
                TempData["success"] = "Đã cập nhật 1 Bộ phim";
                return RedirectToAction("Index");
            }
            return View(phim);
        }
        public IActionResult Delete(int id)
        {
            var phim = _db.Phims.FirstOrDefault(x => x.Id == id);
            if (phim == null)
            {
                return NotFound();
            }
            return View(phim);
        }
        // Xử lý xóa chủng loại
        public IActionResult DeleteConfirmed(int id)
        {
            var phim = _db.Phims.Find(id);
            if (phim == null)
            {
                return NotFound();
            }
            _db.Phims.Remove(phim);
            _db.SaveChanges();
            TempData["success"] = "Category deleted success";
            return RedirectToAction("Index");
        }
    }
}

ExamWeb_ChauMinhVui/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExamWeb_ChauMinhVui/Views/Phim/Add.cshtml
@model Phim


<form asp-action="Add" method="post">
    <h2>Add Phim</h2>
    <hr />
    <div class="form-group">
        <label>Tựa đề</label>
        <input asp-for="TuaDe" class="form-control" />
        <span asp-validation-for="TuaDe" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Diễn Viên </label>
        <input asp-for="DienVien" class="form-control" />
        <span asp-validation-for="DienVien" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Thể loại</label>
        <input type="radio" asp-for="TrongNuoc" value="true" />việt nam
        <input type="radio" asp-for="TrongNuoc" value="false" />nước ngoài
    </div>
    <div class="form-group">
        <label>Thời Lượng</label>
        <input asp-for="ThoiLuong" class="form-control" />
        <span asp-validation-for="ThoiLuong" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>giá vé</label>
        <input asp-for="GiaVe" class="form-control" />
        <span asp-validation-for="GiaVe" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary"> Save </button>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</form>

ExamWeb_ChauMinhVui/Views/Phim/Index.cshtml
@model List<Phim>

<partial name="_ThongBao" />

<div class="row">
    <div class="col-md-6">
        <h2>LIST PHIM</h2>
    </div>
    <div class="col-md-6 text-right">
        <a asp-action="Add" class="btn btn-primary">
            Thêm mới phim
        </a>
    </div>
</div>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Tựa đề </th>
            <th>thể loại</th>
            <th>giá vé </th>
            <th>thời lượng </th>
            <th>Action </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
        <tr>
            <td>@x.TuaDe</td>
            <td>@(x.TrongNuoc ? "việt nam":"nước ngoài")</td>
            <td>@x.GiaVe</td>
            <td>@x.ThoiLuong</td>
            <td>
                <a asp-action="Update" asp-route-id="@x.Id" class="btn btn-success">
                    Sửa
                </a>
                <a asp-action="Delete" asp-route-id="@x.Id" class="btn btn-danger">
                    Xoá
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>

<div class="alert alert-info pt-2">
    Có <b>@ViewBag.SUM </b> Phim trong thư viện _giá vé cao nhất
</div>

ExamWeb_ChauMinhVui/Views/Phim/Update.cshtml
@model Phim


<form asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <h2>Update Phim</h2>
    <div class="form-group">
        <label>Tựa đề</label>
        <input asp-for="TuaDe" class="form-control" />
        <span asp-validation-for="TuaDe" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Diễn Viên </label>
        <input asp-for="DienVien" class="form-control" />
        <span asp-validation-for="DienVien" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Thể loại</label>
        <input type="radio" asp-for="TrongNuoc" value="true" />việt nam
        <input type="radio" asp-for="TrongNuoc" value="false" />nước ngoài
    </div>
    <div class="form-group">
        <label>Thời Lượng</label>
        <input asp-for="ThoiLuong" class="form-control" />
        <span asp-validation-for="ThoiLuong" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>giá vé</label>
        <input asp-for="GiaVe" class="form-control" />
        <span asp-validation-for="GiaVe" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary"> Save </button>
    <a asp-action="Index" class="btn btn-secondary">Back to List</a>
</form>

ExamWeb_ChauMinhVui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExamWeb_ChauMinhVui</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExamWeb_ChauMinhVui</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Phim" asp-action="Index">Phim</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExamWeb_ChauMinhVui - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ExamWeb_ChauMinhVui/Views/Shared/_ThongBao.cshtml
@if (TempData["success"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        Swal.fire({
        title: "@TempData["success"]",
        text: "You clicked the button!",
        icon: "success"
        });
    </script>
}
@if (TempData["error"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        Swal.fire({
        title: "@TempData["error"]",
        text: "You clicked the button!",
        icon: "error"
        });
    </script>
}